version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tagis-api-sam-stack-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gejfo3gxgmk"
s3_prefix = "tagis-api-sam-stack-test"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvironmentClass=Dev"

