AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Template for TAGIS application"

# Template Parameters
Parameters:
  EnvironmentClass:
    Description: Environment (Dev, Stage, Prod)
    Type: String
    AllowedValues: 
      - Dev
      - Stage
      - Prod

# Template resources
Resources:
  ## IAM roles for buckets and RDS 
  #  TagisBucketRole:
  #    Type: AWS::IAM::Role
  #    Properties:
  #      AssumeRolePolicyDocument:
  #        Version: 2012-10-17
  #        Statement:
  #          - Effect: Allow
  #            Principal:
  #            Service:
  #              - "s3.amazonaws.com"
  #            Action:
  #              - "sts:AssumeRole"
  #        Path: "/"
  #  TagisBucketPolicy:
  #    Type: AWS::IAM::Policy
  #    Properties:
  #      PolicyName: "TagisBucket"
  #      PolicyDocument:
  #        Version: "2012-10-17"
  #        Statement:
  #          -
  #            Effect: "Allow"
  #            Action: "*"
  #            Resource: "Tagis-Build-Bucket"
  #        Roles:
  #          -
  #            Ref: "TagisBucketRole"
  #  TagisBucketProfile:
  #    Type: AWS::IAM::InstanceProfile
  #    Properties:
  #      Path: "/"
  #      Roles:
  #        -
  #          Ref: "TagisbucketRole"

  ## S3 buckets
  # S3 bucket for Circle CI builds
#  BuildBucket:
#    Type: AWS::S3::Bucket
#    DeletionPolicy: Retain
#    Properties:
#      BucketName: tagis-build-bucket
#      Tags:
#        -
#          Key: "client"
#          Value: "Advent Group"
#        -
#          Key: "application"
#          Value: "tagis-build"

  # S3 bucket for static website hosting
#  ClientBucket:
#    Type: AWS::S3::Bucket
#    DeletionPolicy: Retain
#    Properties:
#      BucketName: tagis-client
#      Tags:
#        -
#          Key: "client"
#          Value: "Advent Group"
#        -
#          Key: "application"
#          Value: "tagis-client"
#      WebsiteConfiguration:
#        IndexDocument: "index.html"
  
  ## RestAPI base settings
  TagisRestApi: 
    Type: AWS::Serverless::Api
    Properties:
      Name: TagisRestApi
      StageName: !Ref EnvironmentClass
      EndpointConfiguration: EDGE
      Auth:
        ApiKeyRequired: true

  ## API models
  # Store
  StoreModel:
    Type: AWS::ApiGateway::Model
    DependsOn: TagisRestApi
    Properties:
      RestApiId: !Ref TagisRestApi
      ContentType: application/json
      Description: Schema for TAGIS stores
      Name: StoreModel
      Schema:
        $schema: 'http://json-schema.org/draft-04/schema#'
        title: !Sub
          - "OrderModel-${EnvironmentClass}"
          - { EnvironmentClass: !Ref EnvironmentClass }
        type: object
        items:
          type: object
          properties:
            _cid:
              type: integer
            title:
              type: string
            machineTitle:
              type: string
            logoUrl:
              type: string
            address1:
              type: string
            address2:
              type: string
            city:
              type: string
            state:
              type: string
            zip:
              type: string
            contactName:
              type: string
            contactEmail:
              type: string
            contactPhone:
              type: string
            websiteUrl:
              type: string
            companyStore:
              type: string
            emailFromAddress:
              type: string
            receiptEmail:
              type: string
            shippingNotificationEmail:
              type: string
            thankYouEmail:
              type: string
            authToken:
              type: string
            orderApiEndpoint:
              type: string
            productApiEndpoint:
              type: string
      
  # Adding ApiGateway stage
  # Stage and prod exist by default, so need to add dev
  DevApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    DependsOn: TagisRestApi
    Properties:
      StageName: "Dev"
      RestApiId: !Ref TagisRestApi
      DeploymentId: b7716c4ca18eaf847fa295415cab83ef88ff448c
        
  ## API Lambda Functions
  # GetOrders – GET /orders
  GetOrdersFunction:
    Type: AWS::Serverless::Function
    DependsOn: TagisRestApi
    Properties:
      Runtime: dotnetcore2.1
      Handler: tagisApi::tagisApi.Controllers.OrdersController::GetOrders
      Runtime: dotnetcore2.1
      CodeUri: ./src/tagisApi/
      FunctionName: !Sub
        - "tagis-${EnvironmentClass}-GetOrders"
        - { EnvironmentClass: !Ref EnvironmentClass }
      Events:
        GetOrders:
          Type: Api
          Properties:
            Path: /orders
            Method: get

  # GetOrderList – GET /orders/list
  GetOrderListFunction:
    Type: AWS::Serverless::Function
    DependsOn: TagisRestApi
    Properties:
      Runtime: dotnetcore2.1
      Handler: tagisApi::tagisApi.Controllers.OrdersController::GetOrderList
      Runtime: dotnetcore2.1
      CodeUri: ./src/tagisApi/
      FunctionName: !Sub
        - "tagis-${EnvironmentClass}-GetOrderList"
        - { EnvironmentClass: !Ref EnvironmentClass }
      Events:
        GetOrderList:
          Type: Api
          Properties:
            Path: /orders/list
            Method: get

  # GetOrder – GET /orders/{id}
  GetOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: dotnetcore2.1
      Handler: tagisApi::tagisApi.Controllers.OrdersController::GetOrder
      Runtime: dotnetcore2.1
      CodeUri: ./src/tagisApi/
      FunctionName: !Sub
        - "tagis-${EnvironmentClass}-GetOrder"
        - { EnvironmentClass: !Ref EnvironmentClass }
      Events:
        GetOrder:
          Type: Api
          Properties:
            Path: /orders/{id}
            Method: get

  # GetRecentOrders – GET /orders/recent
  GetOrderFunction:
    Type: AWS::Serverless::Function
    DependsOn: TagisRestApi
    Properties:
      Runtime: dotnetcore2.1
      Handler: tagisApi::tagisApi.Controllers.OrdersController::GetRecentOrders
      Runtime: dotnetcore2.1
      CodeUri: ./src/tagisApi/
      FunctionName: !Sub 
        - "tagis-${EnvironmentClass}-GetRecentOrders"
        - { EnvironmentClass: !Ref EnvironmentClass }
      Events:
        GetOrder:
          Type: Api
          Properties:
            Path: /orders/recent
            Method: get

  # PostOrder – POST /orders
  GetOrderFunction:
    Type: AWS::Serverless::Function
    DependsOn: TagisRestApi
    Properties:
      Runtime: dotnetcore2.1
      Handler: tagisApi::tagisApi.Controllers.OrdersController::PostOrder
      Runtime: dotnetcore2.1
      CodeUri: ./src/tagisApi/
      FunctionName: !Sub
        - "tagis-${EnvironmentClass}-PostOrder"
        - { EnvironmentClass: !Ref EnvironmentClass }
      Events:
        GetOrder:
          Type: Api
          Properties:
            Path: /orders
            Method: post