# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.13
# workflows:
  # version: 2
  # build-tagis:
  #   branches:
  #     only:
  #       - master
  #   jobs:
  #     - build-api
  #     - build-client
jobs:
  # Build Angular Client
  build:
    # Set job environment variables
    environment:
      S3BUCKET: tagis-build-bucket-temp
    docker:
      # specify the version you desire here
      - image: circleci/node:10.18.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - checkout
      - run: cd ~/tagisv2/tagis.Client
      - run: npm install
      - run: ng build --configuration="prod"
      - aws-s3/sync:
          from: dist
          to: 's3://${S3BUCKET}/client'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: yarn test